# application.yml

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/demo-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9090