# application.yml

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://postgres:5432/demo-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 600000
#      connection-timeout: 30000
#      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    show-sql: true
    open-in-view: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 9090
#  servlet:
#    context-path: /api

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://keycloak:8080/realms/tenant-1
