server:
  port: 9090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/tenant-1
          jwk-set-uri: http://localhost:8080/realms/tenant-1/protocol/openid-connect/certs

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
    org:
      springframework:
        security: DEBUG
        security.web.access: DEBUG
        security.oauth2: DEBUG
        security.oauth2.server.resource: DEBUG
        web: INFO
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    name: logs/application.log
#    max-size: 10MB
#    max-history: 10